# see: https://codejack.com/2024/10/github-actions-for-net-cicd-setup-guide/
# Note: very basic, I am just a starter here!

name: .NET CI, modified

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      not_needed: src/heos-remote/heos-remote.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    defaults:
      run:
    #    shell: bash
        working-directory: ./src/heos-remote

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Packages to the version given in the project
    - name: Restore dependencies
      run: dotnet restore

    # Build
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.semVer }}

    # Prepare directory for copy deployment
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: heos-remote-systray_winforms-win64-anycpu
        path: ./src/heos-remote/publish
